http:
  host: "0.0.0.0"
  port: "80"

processAPI:
  host: "contactmanagement-process-db-api.us-e2.cloudhub.io"
  port: "80"
  putContact:
    path: "/api/contacts"
  putAddress:
    path: "/api/contacts/address"
  putCommunication:
    path: "/api/contacts/communication"
  postContact:
    path: "/api/contacts"
  getContact:
    path: "/api/contacts"
  deleteContact:
    path: "/api/contacts"
  