#%RAML 1.0 DataType
description: This is used for creating a new user. 
type: object
properties:
  identification:
    type: object
    required: true
    properties:
      firstName: 
        type: string
        required: true
      lastName:
        type: string
        required: true
      dateofBirth:
        type: string
        required: true
      gender:
        type: string
        required: true
      title:
        type: string
        required: true
      email:
        type: string
        required: true
          